# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://rosebetheradomcare.netlify.com/"
languageCode = "en-US"
title = "Rosebeth Era Domestic & Care Referral Agency"

# Metadata
[params]
  author = ""
  description = ""

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "Rosebeth Era Domestic & Care Referral Agency"
  description = ""

# Navigation section
[params.nav]
  mission = "Services"
  services = "Services"
  team = "Client References"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/IMG_20180419_204106_01.jpg"
    [[params.mission.images.list]]
      img = "images/image0000001.jpg"
    [[params.mission.images.list]]
      img = "images/image0000011.jpg"
    [[params.mission.images.list]]
      img = "images/IMG_20180419_204101_01.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Housekeeping"
    subtitle = "We are an employment agency that specializes in job placement. We hire nurse assistants, unlicensed assistive personnel, and house keepers. We are insured and bonded, including workers compensation insurance. We do a thorough criminal background check on all our workers, and assure you a safe environment with our workers. We are strong and very reliable."
    description = "<p>Our housekeeping services include laundry, mopping, sweeping, dusting, window cleaning, emptying trash, washing the bathrooms, cleaning the kitchen, and other household related tasks.</p><p>Our price is unbeatable.</p><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "CNA & Caregiving"
    subtitle = "We are an employment agency that specializes in job placement. We hire nurse assistants, unlicensed assistive personnel, and house keepers. We are insured and bonded, including workers compensation insurance. We do a thorough criminal background check on all our workers, and assure you a safe environment with our workers. We are strong and very reliable."
    description = "<p>We cover oncall CNA/Caregiving services to congregate homes. If any of your certified nurse assistants call off, we can cover them. We primarily serve as a registry agency to cover your shifts.</p><p>Our price is unbeatable.</p><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = false
  video = true
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-present"
    title = "Web Development"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = false

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = false
  title = "Client References"
  description = "Feel free to contact any of our past clients for a reference. Some of the congregate homes we work for include [Royal Haven](http://www.clhfhomes.com/royal-haven.html), Valley Living Center, [Valley View](http://www.valleyviewcongregate.com/), Healthy Life Congregate Care, [Fenton Villa](http://www.clhfhomes.com/fenton.html), and Home of Compassion."

  [[params.team.item]]
    name = "Paul Rinehard"
    position = "CLHF Homes"
    description = "(920) 634-6768"
    img = "images/person1.jpg"

  [[params.team.item]]
    name = "Omar"
    position = "Corbin Congregate"
    description = "(323) 898-8680"
    img = "images/person2.jpg"

  [[params.team.item]]
    name = "Rizza"
    position = "Fenton Villa"
    description = "(747) 248-9714"
    img = "images/person3.jpg"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person3.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Do not hesitate to contact us!<br>We will be pleased to assist you. Contact us at: (424) 303-0437"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2018 Free HTML5 Template. All Rights Reserved. <br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small><br><small>Deployed by <a href='https://xaviablaza.com' target='_blank'>Xavi Ablaza</a></small></p>"

  
